application: qmacro-coffeeshop
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /media
  static_dir: media

- url: /docu.html
  static_files: docu.html
  upload: docu.html

- url: /.*
  script: coffeeshop.py
